/*
 * Copyright (c) 2012-present Snowplow Analytics Ltd.
 * All rights reserved.
 *
 * This software is made available by Snowplow Analytics, Ltd.,
 * under the terms of the Snowplow Limited Use License Agreement, Version 1.1
 * located at https://docs.snowplow.io/limited-use-license-1.1
 * BY INSTALLING, DOWNLOADING, ACCESSING, USING OR DISTRIBUTING ANY PORTION
 * OF THE SOFTWARE, YOU AGREE TO THE TERMS OF SUCH LICENSE AGREEMENT.
 */
package com.snowplowanalytics.snowplow.enrich.streams.kinesis

import java.nio.file.Paths
import java.util.UUID

import scala.concurrent.duration.DurationInt

import org.specs2.Specification

import cats.Id

import cats.effect.{ExitCode, IO}

import cats.effect.testing.specs2.CatsEffect

import org.http4s.Uri

import com.comcast.ip4s.Port

import com.snowplowanalytics.snowplow.runtime.Metrics.StatsdConfig
import com.snowplowanalytics.snowplow.runtime.{AcceptedLicense, ConfigParser, HttpClient, Telemetry}

import com.snowplowanalytics.snowplow.sinks.kinesis.{KinesisSinkConfig, KinesisSinkConfigM}
import com.snowplowanalytics.snowplow.sources.kinesis.KinesisSourceConfig

import com.snowplowanalytics.snowplow.kinesis.BackoffPolicy

import com.snowplowanalytics.snowplow.enrich.common.SpecHelpers.{adaptersSchemas, atomicFieldLimitsDefaults}
import com.snowplowanalytics.snowplow.enrich.common.enrichments.AtomicFields

import com.snowplowanalytics.snowplow.enrich.streams.common.Config

class KinesisConfigSpec extends Specification with CatsEffect {

  def is = s2"""
  Config parse should be able to parse
    minimal kinesis config $minimal
    reference kinesis config $reference
  """

  private def minimal =
    assert(
      resource = "/config.kinesis.next.minimal.hocon",
      expectedResult = Right(
        KinesisConfigSpec.minimalConfig
      )
    )

  private def reference =
    assert(
      resource = "/config.kinesis.next.reference.hocon",
      expectedResult = Right(
        KinesisConfigSpec.referenceConfig
      )
    )

  private def assert(resource: String, expectedResult: Either[ExitCode, Config[KinesisSourceConfig, KinesisSinkConfig, EmptyConfig]]) = {
    val path = Paths.get(getClass.getResource(resource).toURI)
    ConfigParser.configFromFile[IO, Config[KinesisSourceConfig, KinesisSinkConfig, EmptyConfig]](path).value.map { result =>
      result must beEqualTo(expectedResult)
    }
  }
}

object KinesisConfigSpec {
  private val minimalConfig = Config[KinesisSourceConfig, KinesisSinkConfig, EmptyConfig](
    license = AcceptedLicense(),
    input = KinesisSourceConfig(
      appName = "snowplow-enrich",
      streamName = "snowplow-collector-payloads",
      workerIdentifier = "testWorkerId",
      initialPosition = KinesisSourceConfig.InitialPosition.Latest,
      retrievalMode = KinesisSourceConfig.Retrieval.Polling(1000),
      customEndpoint = None,
      dynamodbCustomEndpoint = None,
      cloudwatchCustomEndpoint = None,
      leaseDuration = 10.seconds,
      maxLeasesToStealAtOneTimeFactor = BigDecimal(2),
      checkpointThrottledBackoffPolicy = BackoffPolicy(minBackoff = 100.millis, maxBackoff = 1.second),
      debounceCheckpoints = 10.seconds
    ),
    output = Config.Output(
      enriched = Config.SinkWithMetadata(
        sink = KinesisSinkConfigM[Id](
          streamName = "snowplow-enriched",
          throttledBackoffPolicy = BackoffPolicy(minBackoff = 100.millis, maxBackoff = 1.second),
          recordLimit = 500,
          byteLimit = 5242880,
          customEndpoint = None
        ),
        maxRecordSize = 1000000,
        partitionKey = None,
        attributes = None
      ),
      failed = None,
      bad = Config.SinkWithMetadata(
        sink = KinesisSinkConfigM[Id](
          streamName = "snowplow-bad",
          throttledBackoffPolicy = BackoffPolicy(minBackoff = 100.millis, maxBackoff = 1.second),
          recordLimit = 500,
          byteLimit = 5242880,
          customEndpoint = None
        ),
        maxRecordSize = 1000000,
        partitionKey = None,
        attributes = None
      )
    ),
    cpuParallelismFraction = BigDecimal(0.75),
    monitoring = Config.Monitoring(
      metrics = Config.Metrics(None),
      sentry = None,
      healthProbe = Config.HealthProbe(port = Port.fromInt(8000).get, unhealthyLatency = 2.minutes)
    ),
    assetsUpdatePeriod = 7.days,
    http = Config.Http(HttpClient.Config(maxConnectionsPerServer = 4)),
    validation = Config.Validation(
      acceptInvalid = false,
      atomicFieldsLimits = AtomicFields.from(atomicFieldLimitsDefaults),
      maxJsonDepth = 50
    ),
    telemetry = Telemetry.Config(
      disable = false,
      interval = 15.minutes,
      collectorUri = "collector-g.snowplowanalytics.com",
      collectorPort = 443,
      secure = true,
      userProvidedId = None,
      autoGeneratedId = None,
      instanceId = None,
      moduleName = None,
      moduleVersion = None
    ),
    metadata = None,
    blobClients = EmptyConfig(),
    adaptersSchemas = adaptersSchemas
  )

  private val referenceConfig = Config[KinesisSourceConfig, KinesisSinkConfig, EmptyConfig](
    license = AcceptedLicense(),
    input = KinesisSourceConfig(
      appName = "snowplow-enrich",
      streamName = "snowplow-collector-payloads",
      workerIdentifier = "testWorkerId",
      initialPosition = KinesisSourceConfig.InitialPosition.TrimHorizon,
      retrievalMode = KinesisSourceConfig.Retrieval.Polling(1000),
      customEndpoint = None,
      dynamodbCustomEndpoint = None,
      cloudwatchCustomEndpoint = None,
      leaseDuration = 10.seconds,
      maxLeasesToStealAtOneTimeFactor = BigDecimal(2),
      checkpointThrottledBackoffPolicy = BackoffPolicy(minBackoff = 100.millis, maxBackoff = 1.second),
      debounceCheckpoints = 10.seconds
    ),
    output = Config.Output(
      enriched = Config.SinkWithMetadata(
        sink = KinesisSinkConfigM[Id](
          streamName = "snowplow-enriched",
          throttledBackoffPolicy = BackoffPolicy(minBackoff = 100.millis, maxBackoff = 1.second),
          recordLimit = 500,
          byteLimit = 5242880,
          customEndpoint = None
        ),
        maxRecordSize = 1000000,
        partitionKey = Some("user_id"),
        attributes = None
      ),
      failed = Some(
        Config.SinkWithMetadata(
          sink = KinesisSinkConfigM[Id](
            streamName = "snowplow-failed",
            throttledBackoffPolicy = BackoffPolicy(minBackoff = 100.millis, maxBackoff = 1.second),
            recordLimit = 500,
            byteLimit = 5242880,
            customEndpoint = None
          ),
          maxRecordSize = 1000000,
          partitionKey = None,
          attributes = None
        )
      ),
      bad = Config.SinkWithMetadata(
        sink = KinesisSinkConfigM[Id](
          streamName = "snowplow-bad",
          throttledBackoffPolicy = BackoffPolicy(minBackoff = 100.millis, maxBackoff = 1.second),
          recordLimit = 500,
          byteLimit = 5242880,
          customEndpoint = None
        ),
        maxRecordSize = 1000000,
        partitionKey = None,
        attributes = None
      )
    ),
    cpuParallelismFraction = BigDecimal(0.75),
    monitoring = Config.Monitoring(
      metrics = Config.Metrics(
        statsd = Some(
          StatsdConfig(
            hostname = "127.0.0.1",
            port = 8125,
            tags = Map("env" -> "prod"),
            period = 1.minute,
            prefix = "snowplow.enrich"
          )
        )
      ),
      sentry = Some(Config.SentryM[Id](dsn = "https://public@sentry.example.com/1", tags = Map("myTag" -> "xyz"))),
      healthProbe = Config.HealthProbe(
        port = Port.fromInt(8000).get,
        unhealthyLatency = 2.minutes
      )
    ),
    assetsUpdatePeriod = 7.days,
    http = Config.Http(HttpClient.Config(maxConnectionsPerServer = 4)),
    validation = Config.Validation(
      acceptInvalid = false,
      atomicFieldsLimits = AtomicFields.from(atomicFieldLimitsDefaults ++ Map("app_id" -> 5, "mkt_clickid" -> 100000)),
      maxJsonDepth = 50
    ),
    telemetry = Telemetry.Config(
      disable = false,
      interval = 15.minutes,
      collectorUri = "collector-g.snowplowanalytics.com",
      collectorPort = 443,
      secure = true,
      userProvidedId = Some("my_pipeline"),
      autoGeneratedId = Some("hfy67e5ydhtrd"),
      instanceId = Some("665bhft5u6udjf"),
      moduleName = Some("enrich-kinesis-ce"),
      moduleVersion = Some("1.0.0")
    ),
    metadata = Some(
      Config.MetadataM[Id](
        endpoint = Uri.unsafeFromString("https://my_pipeline.my_domain.com/iglu"),
        interval = 5.minutes,
        organizationId = UUID.fromString("c5f3a09f-75f8-4309-bec5-fea560f78455"),
        pipelineId = UUID.fromString("75a13583-5c99-40e3-81fc-541084dfc784"),
        maxBodySize = 150000
      )
    ),
    blobClients = EmptyConfig(),
    adaptersSchemas = adaptersSchemas
  )
}
