/*
 * Copyright (c) 2012-present Snowplow Analytics Ltd.
 * All rights reserved.
 *
 * This software is made available by Snowplow Analytics, Ltd.,
 * under the terms of the Snowplow Limited Use License Agreement, Version 1.1
 * located at https://docs.snowplow.io/limited-use-license-1.1
 * BY INSTALLING, DOWNLOADING, ACCESSING, USING OR DISTRIBUTING ANY PORTION
 * OF THE SOFTWARE, YOU AGREE TO THE TERMS OF SUCH LICENSE AGREEMENT.
 */
package com.snowplowanalytics.snowplow.enrich.streams.nsq

import java.nio.file.Paths
import java.util.UUID

import scala.concurrent.duration.DurationInt

import org.specs2.Specification

import cats.Id
import cats.effect.{ExitCode, IO}

import cats.effect.testing.specs2.CatsEffect

import org.http4s.Uri

import com.comcast.ip4s.Port

import com.snowplowanalytics.snowplow.runtime.Metrics.StatsdConfig
import com.snowplowanalytics.snowplow.runtime.{AcceptedLicense, ConfigParser, Retrying, Telemetry}

import com.snowplowanalytics.snowplow.streams.nsq.{BackoffPolicy, NsqSinkConfig, NsqSinkConfigM, NsqSourceConfig}

import com.snowplowanalytics.snowplow.enrich.common.SpecHelpers.{adaptersSchemas, atomicFieldLimitsDefaults}
import com.snowplowanalytics.snowplow.enrich.common.enrichments.AtomicFields

import com.snowplowanalytics.snowplow.enrich.cloudutils.azure.AzureStorageConfig

import com.snowplowanalytics.snowplow.enrich.streams.common.Config

class NsqConfigSpec extends Specification with CatsEffect {

  def is = s2"""
  Config parse should be able to parse
    minimal nsq config $minimal
    reference nsq config $reference
  """

  private def minimal =
    assert(
      resource = "/config.nsq.next.minimal.hocon",
      expectedResult = Right(
        NsqConfigSpec.minimalConfig
      )
    )

  private def reference =
    assert(
      resource = "/config.nsq.next.reference.hocon",
      expectedResult = Right(
        NsqConfigSpec.referenceConfig
      )
    )

  private def assert(
    resource: String,
    expectedResult: Either[ExitCode, Config[EmptyConfig, NsqSourceConfig, NsqSinkConfig, AzureStorageConfig]]
  ) = {
    val path = Paths.get(getClass.getResource(resource).toURI)
    ConfigParser.configFromFile[IO, Config[EmptyConfig, NsqSourceConfig, NsqSinkConfig, AzureStorageConfig]](path).value.map { result =>
      result must beEqualTo(expectedResult)
    }
  }
}

object NsqConfigSpec {
  private val minimalConfig = Config[EmptyConfig, NsqSourceConfig, NsqSinkConfig, AzureStorageConfig](
    license = AcceptedLicense(),
    input = NsqSourceConfig(
      topic = "collector-payloads",
      channel = "collector-payloads-channel",
      lookupHost = "127.0.0.1",
      lookupPort = 4161,
      maxBufferQueueSize = 3000
    ),
    output = Config.Output(
      good = Config.SinkWithMetadata(
        sink = NsqSinkConfigM[Id](
          topic = "enriched",
          nsqdHost = "127.0.0.1",
          nsqdPort = 4150,
          byteLimit = 5000000,
          backoffPolicy = BackoffPolicy(minBackoff = 100.milliseconds, maxBackoff = 10.seconds, maxRetries = Some(10))
        ),
        maxRecordSize = 1000000,
        partitionKey = None,
        attributes = Nil
      ),
      failed = None,
      bad = Config.SinkWithMetadata(
        sink = NsqSinkConfigM[Id](
          topic = "bad",
          nsqdHost = "127.0.0.1",
          nsqdPort = 4150,
          byteLimit = 5000000,
          backoffPolicy = BackoffPolicy(minBackoff = 100.milliseconds, maxBackoff = 10.seconds, maxRetries = Some(10))
        ),
        maxRecordSize = 1000000,
        partitionKey = None,
        attributes = Nil
      )
    ),
    streams = EmptyConfig(),
    cpuParallelismFraction = BigDecimal(0.75),
    monitoring = Config.Monitoring(
      metrics = Config.Metrics(None),
      sentry = None,
      healthProbe = Config.HealthProbe(port = Port.fromInt(8000).get, unhealthyLatency = 2.minutes)
    ),
    assetsUpdatePeriod = 7.days,
    validation = Config.Validation(
      acceptInvalid = false,
      atomicFieldsLimits = AtomicFields.from(atomicFieldLimitsDefaults),
      maxJsonDepth = 50,
      exitOnJsCompileError = true
    ),
    telemetry = Telemetry.Config(
      disable = false,
      interval = 15.minutes,
      collectorUri = Uri.unsafeFromString("https://collector-g.snowplowanalytics.com"),
      userProvidedId = None,
      autoGeneratedId = None,
      instanceId = None,
      moduleName = None,
      moduleVersion = None
    ),
    metadata = None,
    identity = None,
    blobClients = AzureStorageConfig(Nil),
    adaptersSchemas = adaptersSchemas
  )

  private val referenceConfig = Config[EmptyConfig, NsqSourceConfig, NsqSinkConfig, AzureStorageConfig](
    license = AcceptedLicense(),
    input = NsqSourceConfig(
      topic = "collector-payloads",
      channel = "collector-payloads-channel",
      lookupHost = "127.0.0.1",
      lookupPort = 4161,
      maxBufferQueueSize = 3000
    ),
    output = Config.Output(
      good = Config.SinkWithMetadata(
        sink = NsqSinkConfigM[Id](
          topic = "enriched",
          nsqdHost = "127.0.0.1",
          nsqdPort = 4150,
          byteLimit = 5000000,
          backoffPolicy = BackoffPolicy(minBackoff = 100.milliseconds, maxBackoff = 10.seconds, maxRetries = Some(10))
        ),
        maxRecordSize = 1000000,
        partitionKey = None,
        attributes = Nil
      ),
      failed = Some(
        Config.SinkWithMetadata(
          sink = NsqSinkConfigM[Id](
            topic = "failed",
            nsqdHost = "127.0.0.1",
            nsqdPort = 4150,
            byteLimit = 5000000,
            backoffPolicy = BackoffPolicy(minBackoff = 100.milliseconds, maxBackoff = 10.seconds, maxRetries = Some(10))
          ),
          maxRecordSize = 1000000,
          partitionKey = None,
          attributes = Nil
        )
      ),
      bad = Config.SinkWithMetadata(
        sink = NsqSinkConfigM[Id](
          topic = "bad",
          nsqdHost = "127.0.0.1",
          nsqdPort = 4150,
          byteLimit = 5000000,
          backoffPolicy = BackoffPolicy(minBackoff = 100.milliseconds, maxBackoff = 10.seconds, maxRetries = Some(10))
        ),
        maxRecordSize = 1000000,
        partitionKey = None,
        attributes = Nil
      )
    ),
    streams = EmptyConfig(),
    cpuParallelismFraction = BigDecimal(0.75),
    monitoring = Config.Monitoring(
      metrics = Config.Metrics(
        statsd = Some(
          StatsdConfig(
            hostname = "127.0.0.1",
            port = 8125,
            tags = Map("env" -> "prod"),
            period = 1.minute,
            prefix = "snowplow.enrich"
          )
        )
      ),
      sentry = Some(Config.SentryM[Id](dsn = "https://public@sentry.example.com/1", tags = Map("myTag" -> "xyz"))),
      healthProbe = Config.HealthProbe(
        port = Port.fromInt(8000).get,
        unhealthyLatency = 2.minutes
      )
    ),
    assetsUpdatePeriod = 7.days,
    validation = Config.Validation(
      acceptInvalid = false,
      atomicFieldsLimits = AtomicFields.from(atomicFieldLimitsDefaults ++ Map("app_id" -> 5, "mkt_clickid" -> 100000)),
      maxJsonDepth = 50,
      exitOnJsCompileError = true
    ),
    telemetry = Telemetry.Config(
      disable = false,
      interval = 15.minutes,
      collectorUri = Uri.unsafeFromString("https://collector-g.snowplowanalytics.com"),
      userProvidedId = Some("my_pipeline"),
      autoGeneratedId = Some("hfy67e5ydhtrd"),
      instanceId = Some("665bhft5u6udjf"),
      moduleName = Some("enrich-kinesis-ce"),
      moduleVersion = Some("1.0.0")
    ),
    metadata = Some(
      Config.MetadataM[Id](
        endpoint = Uri.unsafeFromString("https://my_pipeline.my_domain.com/iglu"),
        interval = 5.minutes,
        organizationId = UUID.fromString("c5f3a09f-75f8-4309-bec5-fea560f78455"),
        pipelineId = UUID.fromString("75a13583-5c99-40e3-81fc-541084dfc784"),
        maxBodySize = 150000
      )
    ),
    identity = Some(
      Config.IdentityM[Id](
        endpoint = Uri.unsafeFromString("http://identity-api"),
        concurrency = 10,
        username = "snowplow",
        password = "sn0wp10w",
        retries = Retrying.Config.ForTransient(100.millis, 3)
      )
    ),
    blobClients = AzureStorageConfig(
      List(
        AzureStorageConfig.Account("storageAccount1", None),
        AzureStorageConfig.Account("storageAccount2", Some(AzureStorageConfig.Account.Auth.DefaultCredentialsChain)),
        AzureStorageConfig.Account("storageAccount3", Some(AzureStorageConfig.Account.Auth.SasToken("tokenValue")))
      )
    ),
    adaptersSchemas = adaptersSchemas
  )
}
