/*
 * Copyright (c) 2012-present Snowplow Analytics Ltd.
 * All rights reserved.
 *
 * This software is made available by Snowplow Analytics, Ltd.,
 * under the terms of the Snowplow Limited Use License Agreement, Version 1.1
 * located at https://docs.snowplow.io/limited-use-license-1.1
 * BY INSTALLING, DOWNLOADING, ACCESSING, USING OR DISTRIBUTING ANY PORTION
 * OF THE SOFTWARE, YOU AGREE TO THE TERMS OF SUCH LICENSE AGREEMENT.
 */
package com.snowplowanalytics.snowplow.enrich.streams.pubsub

import java.nio.file.Paths
import java.util.UUID

import scala.concurrent.duration.DurationInt

import org.specs2.Specification

import cats.Id
import cats.implicits._
import cats.effect.{ExitCode, IO}

import cats.effect.testing.specs2.CatsEffect

import org.http4s.Uri

import com.comcast.ip4s.Port

import com.snowplowanalytics.snowplow.runtime.Metrics.StatsdConfig
import com.snowplowanalytics.snowplow.runtime.{AcceptedLicense, ConfigParser, HttpClient, Telemetry}

import com.snowplowanalytics.snowplow.streams.pubsub.{GcpUserAgent, PubsubSinkConfig, PubsubSinkConfigM, PubsubSourceConfig, PubsubFactoryConfig}

import com.snowplowanalytics.snowplow.enrich.common.SpecHelpers.{adaptersSchemas, atomicFieldLimitsDefaults}
import com.snowplowanalytics.snowplow.enrich.common.enrichments.AtomicFields
import com.snowplowanalytics.snowplow.enrich.common.outputs.EnrichedEvent

import com.snowplowanalytics.snowplow.enrich.streams.common.Config

class PubsubConfigSpec extends Specification with CatsEffect {

  def is = s2"""
  Config parse should be able to parse
    minimal pubsub config $minimal
    reference pubsub config $reference
  """

  private def minimal =
    assert(
      resource = "/config.pubsub.next.minimal.hocon",
      expectedResult = Right(
        PubsubConfigSpec.minimalConfig
      )
    )

  private def reference =
    assert(
      resource = "/config.pubsub.next.reference.hocon",
      expectedResult = Right(
        PubsubConfigSpec.referenceConfig
      )
    )

  private def assert(resource: String, expectedResult: Either[ExitCode, Config[PubsubFactoryConfig, PubsubSourceConfig, PubsubSinkConfig, EmptyConfig]]) = {
    val path = Paths.get(getClass.getResource(resource).toURI)
    ConfigParser.configFromFile[IO, Config[PubsubFactoryConfig, PubsubSourceConfig, PubsubSinkConfig, EmptyConfig]](path).value.map { result =>
      result must beEqualTo(expectedResult)
    }
  }
}

object PubsubConfigSpec {
  private val minimalConfig = Config[PubsubFactoryConfig, PubsubSourceConfig, PubsubSinkConfig, EmptyConfig](
    license = AcceptedLicense(),
    input = PubsubSourceConfig(
      subscription = PubsubSourceConfig.Subscription("myproject", "snowplow-collector-payloads"),
      parallelPullFactor      = 0.5,
      durationPerAckExtension = 60.seconds,
      minRemainingAckDeadline = 0.1,
      maxMessagesPerPull      = 1000,
      debounceRequests        = 100.millis
    ),
    output = Config.Output(
      good = Config.SinkWithMetadata(
        sink = PubsubSinkConfigM[Id](
          topic                = PubsubSinkConfig.Topic("myproject", "snowplow-enriched"),
          batchSize            = 1000,
          requestByteThreshold = 1000000,
        ),
        maxRecordSize = 8000000,
        partitionKey = None,
        attributes = Nil
      ),
      failed = None,
      bad = Config.SinkWithMetadata(
        sink = PubsubSinkConfigM[Id](
          topic                = PubsubSinkConfig.Topic("myproject", "snowplow-bad"),
          batchSize            = 1000,
          requestByteThreshold = 1000000
        ),
        maxRecordSize = 10000000,
        partitionKey = None,
        attributes = Nil
      )
    ),
    streams = PubsubFactoryConfig(gcpUserAgent = GcpUserAgent("Snowplow OSS", "enrich")),
    cpuParallelismFraction = BigDecimal(0.75),
    monitoring = Config.Monitoring(
      metrics = Config.Metrics(None),
      sentry = None,
      healthProbe = Config.HealthProbe(port = Port.fromInt(8000).get, unhealthyLatency = 2.minutes)
    ),
    assetsUpdatePeriod = 7.days,
    http = Config.Http(HttpClient.Config(maxConnectionsPerServer = 4)),
    validation = Config.Validation(
      acceptInvalid = false,
      atomicFieldsLimits = AtomicFields.from(atomicFieldLimitsDefaults),
      maxJsonDepth = 50,
      exitOnJsCompileError = true
    ),
    telemetry = Telemetry.Config(
      disable = false,
      interval = 15.minutes,
      collectorUri = Uri.unsafeFromString("https://collector-g.snowplowanalytics.com"),
      userProvidedId = None,
      autoGeneratedId = None,
      instanceId = None,
      moduleName = None,
      moduleVersion = None
    ),
    metadata = None,
    blobClients = EmptyConfig(),
    adaptersSchemas = adaptersSchemas,
  )

  private val referenceConfig = Config[PubsubFactoryConfig, PubsubSourceConfig, PubsubSinkConfig, EmptyConfig](
    license = AcceptedLicense(),
    input = PubsubSourceConfig(
      subscription = PubsubSourceConfig.Subscription("myproject", "snowplow-collector-payloads"),
      parallelPullFactor      = 0.5,
      durationPerAckExtension = 60.seconds,
      minRemainingAckDeadline = 0.1,
      maxMessagesPerPull      = 1000,
      debounceRequests        = 100.millis
    ),
    output = Config.Output(
      good = Config.SinkWithMetadata(
        sink = PubsubSinkConfigM[Id](
          topic                = PubsubSinkConfig.Topic("myproject", "snowplow-enriched"),
          batchSize            = 100,
          requestByteThreshold = 1000000,
        ),
        maxRecordSize = 8000000,
        partitionKey = None,
        attributes = List(EnrichedEvent.atomicFields.find(_.getName === "app_id").get)
      ),
      failed = Some(
        Config.SinkWithMetadata(
          sink = PubsubSinkConfigM[Id](
            topic                = PubsubSinkConfig.Topic("myproject", "snowplow-failed"),
            batchSize            = 100,
            requestByteThreshold = 1000000,
          ),
          maxRecordSize = 10000000,
          partitionKey = None,
          attributes = Nil
        )
      ),
      bad = Config.SinkWithMetadata(
        sink = PubsubSinkConfigM[Id](
          topic                = PubsubSinkConfig.Topic("myproject", "snowplow-bad"),
          batchSize            = 100,
          requestByteThreshold = 1000000,
        ),
        maxRecordSize = 10000000,
        partitionKey = None,
        attributes = Nil
      )
    ),
    streams = PubsubFactoryConfig(gcpUserAgent = GcpUserAgent("Snowplow OSS", "enrich")),
    cpuParallelismFraction = BigDecimal(0.75),
    monitoring = Config.Monitoring(
      metrics = Config.Metrics(
        statsd = Some(
          StatsdConfig(
            hostname = "127.0.0.1",
            port = 8125,
            tags = Map("env" -> "prod"),
            period = 1.minute,
            prefix = "snowplow.enrich"
          )
        )
      ),
      sentry = Some(Config.SentryM[Id](dsn = "https://public@sentry.example.com/1", tags = Map("myTag" -> "xyz"))),
      healthProbe = Config.HealthProbe(
        port = Port.fromInt(8000).get,
        unhealthyLatency = 2.minutes
      )
    ),
    assetsUpdatePeriod = 7.days,
    http = Config.Http(HttpClient.Config(maxConnectionsPerServer = 4)),
    validation = Config.Validation(
      acceptInvalid = false,
      atomicFieldsLimits = AtomicFields.from(atomicFieldLimitsDefaults ++ Map("app_id" -> 5, "mkt_clickid" -> 100000)),
      maxJsonDepth = 50,
      exitOnJsCompileError = true
    ),
    telemetry = Telemetry.Config(
      disable = false,
      interval = 15.minutes,
      collectorUri = Uri.unsafeFromString("collector-g.snowplowanalytics.com"),
      userProvidedId = Some("my_pipeline"),
      autoGeneratedId = Some("hfy67e5ydhtrd"),
      instanceId = Some("665bhft5u6udjf"),
      moduleName = Some("enrich-kinesis-ce"),
      moduleVersion = Some("1.0.0")
    ),
    metadata = Some(
      Config.MetadataM[Id](
        endpoint = Uri.unsafeFromString("https://my_pipeline.my_domain.com/iglu"),
        interval = 5.minutes,
        organizationId = UUID.fromString("c5f3a09f-75f8-4309-bec5-fea560f78455"),
        pipelineId = UUID.fromString("75a13583-5c99-40e3-81fc-541084dfc784"),
        maxBodySize = 150000
      )
    ),
    blobClients = EmptyConfig(),
    adaptersSchemas = adaptersSchemas
  )
}
